server:
  port: 9191

spring:
  application:
    name: API-GATEWAAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: USER-SERVICE
                fallbackuri: forward:/userServiceFallback
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
              - Path=/departments/**
          filters:
            - name: CircuitBreaker
              args:
                name: DEPARTMENT-SERVICE
                fallbackuri: forward:/departmentServiceFallback
        - id: ADDRESS-SERVICE
          uri: lb://ADDRESS-SERVICE
          predicates:
              - Path=/address/**
          filters:
            - name: CircuitBreaker
              args:
                name: ADDRESS-SERVICE
                fallbackuri: forward:/addressServiceFallback

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
management:
  endpoints:
    web:
      exposure:
        include: hustrix.stream
